### ISSUE TITLE
Simulation terminates when jettisoned part destroyed (1.1)

### ISSUE THREAD

**Issue by cherrydev** [linuxgurugamer/KRASH#1]
I was simulating a re-entry, starting in orbit of Kerbin and de-orbiting, then staging.  When a staged part hit the atmosphere it was destroyed and the simulation stopped.

**Comment by linuxgurugamer** [comment]
What version of KSP are you running?

This bug was fixed in the update for 1.1, if you are running 1.0.5, I 
can't fix it right now.

If you are using 1.1, then please make sure you have the latest version 
of KRASH downloaded (get it from Github releases)

Thanks

LGG

**Comment by cherrydev** [comment]
Sorry, I thought I indicated that it was the 1.1 release in the title of the issue but I should have been more clear, I was tired when I wrote this.  Is the "Test version for 1.1 available here" link in the forum post not the same as the "d1774df" release here on GitHub? I'll give it a try now and see if I have the same problem...

**Comment by cherrydev** [comment]
I -think- this is fixed in the d1774df release?

**Comment by linuxgurugamer** [comment]
Yes, please confirm that you either or are not still having the problem, with the latest release.
thanks

**Comment by linuxgurugamer** [comment]
Closing, reopen if it happens again
